# Generated by Django 4.2.30 on 2026-05-28 09:49

import apps.assets.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.assets.models.asset_upload_path, verbose_name='文件')),
                ('asset_type', models.CharField(choices=[('image', '图片'), ('model', '3D模型'), ('texture', '材质贴图'), ('template', '设计模板'), ('document', '文档')], max_length=20, verbose_name='资源类型')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
            ],
            options={
                'verbose_name': '资源文件',
                'verbose_name_plural': '资源文件',
                'db_table': 'assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
