# Generated by Django 4.2.30 on 2026-05-28 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='素材名称')),
                ('category', models.CharField(choices=[('color', '配色方案'), ('pattern', '图案'), ('texture', '材质纹理'), ('logo', 'Logo/标识'), ('sticker', '贴纸'), ('shape', '形状')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('preview_image', models.ImageField(upload_to='materials/preview/%Y/%m/', verbose_name='预览图')),
                ('source_file', models.FileField(blank=True, upload_to='materials/source/%Y/%m/', verbose_name='源文件')),
                ('properties', models.TextField(blank=True, default='{}', verbose_name='属性')),
                ('is_official', models.BooleanField(default=False, verbose_name='官方素材')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '素材',
                'verbose_name_plural': '素材',
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
