# Generated by Django 4.2.30 on 2026-05-28 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('category', models.CharField(choices=[('professional', '专业竞技'), ('leisure', '休闲娱乐'), ('custom', '定制系列'), ('tournament', '赛事限定')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('preview_image', models.ImageField(upload_to='templates/preview/%Y/%m/', verbose_name='预览图')),
                ('template_data', models.TextField(default='{}', help_text='默认元素/布局/参数', verbose_name='模板数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'db_table': 'templates',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
